name: Jadx
on: workflow_dispatch
jobs:
  build:
    name: Jadx is Decompiling ApkTool
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
    
      - name: Downloading and Setting Up Jadx
        run: wget https://github.com/skylot/jadx/releases/download/v1.3.4/jadx-1.3.4.zip && unzip jadx-1.3.4.zip 
        
      - name: Grant execute permission to Jadx and Setting 
        run: chmod +x bin/*
      - name: Running Given Task
        run: export PATH=$PATH:$GITHUB_WORKSPACE/bin && jadx Tasks/Apktool M_2.4.0-211203.apk -d Completed 
      - name: Uploading Decompiled File
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: Decompiled Files Of ApkTool
          path: Completed
